name: proyecto_final_dam
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  firebase_auth: ^4.17.5
  firebase_core: ^2.25.5
  flutter:
    sdk: flutter
  flutter_slidable: ^3.0.1
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
