// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoK0tkqDCQbx2ixLSYW_0evcsOx9njkBY',
    appId: '1:800129430252:web:85f53a1a2f74e9334aabc9',
    messagingSenderId: '800129430252',
    projectId: 'todoapp-a8c96',
    authDomain: 'todoapp-a8c96.firebaseapp.com',
    storageBucket: 'todoapp-a8c96.appspot.com',
    measurementId: 'G-ZEG06WJ9W8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDIxJtDtPY3PFIe1xb3jcsudDsk2zfl1M',
    appId: '1:800129430252:android:758bd7a8ca9a3e8b4aabc9',
    messagingSenderId: '800129430252',
    projectId: 'todoapp-a8c96',
    storageBucket: 'todoapp-a8c96.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0P5FWTmgF1ASlMqZ5MA3oF1Q24uUPfkw',
    appId: '1:800129430252:ios:5b296e009be3d0e14aabc9',
    messagingSenderId: '800129430252',
    projectId: 'todoapp-a8c96',
    storageBucket: 'todoapp-a8c96.appspot.com',
    iosBundleId: 'com.example.proyectoFinalDam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0P5FWTmgF1ASlMqZ5MA3oF1Q24uUPfkw',
    appId: '1:800129430252:ios:cbfed14386acb3da4aabc9',
    messagingSenderId: '800129430252',
    projectId: 'todoapp-a8c96',
    storageBucket: 'todoapp-a8c96.appspot.com',
    iosBundleId: 'com.example.proyectoFinalDam.RunnerTests',
  );
}
